initial setup
Certivity/take-home-starter pull request #1
Opened 2023-10-27 12:43 UTC by patrick-mularczyk

2023-10-31 10:13 UTC, rotanimlu approved these changes

2023-10-31 11:25 UTC, rotanimlu requested changes
mongo was missing rest is working fine

2023-10-31 11:25 UTC, rotanimlu commented on README.md
> +pnpm install
npm

2023-10-31 11:25 UTC, rotanimlu commented on README.md
> +
Mongo section is missing: 

- install Docker
- docker pull mongo
- docker run -d --name my-mongodb-container -p 27017:27017 mongo

2023-11-06 08:54 UTC, patrick-mularczyk commented on README.md
> +pnpm install
https://pnpm.io/

2023-11-06 08:57 UTC, patrick-mularczyk commented on README.md
> +
Done

2023-11-06 08:59 UTC, An-Huynh-Certivity approved these changes

2023-11-06 09:16 UTC, rotanimlu approved these changes

2023-11-06 09:26 UTC, merged